server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://10.140.0.8:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://34.125.160.118:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://34.125.160.118:1003
    cart:
      path: /cart/**
      url: http://34.125.160.118:1004/api/v1
