def home="https://github.com/srinath-17/Micro_services/edit/main/micro-service-starter/docker_code/offers-microservice-spring-boot"
pipeline {
    agent any
    stages{
        stage("checkout"){
            steps{
                git branch:"main",url:"https://github.com/srinath-17/Micro_services.git"
            }
        }
        stage("build Docker image"){
            steps{
                sh "docker rm -f uppusrinath/offers-microservice-spring-boot:${BUILD_NUMBER} ."
                sh "docker build -t uppusrinath/offers-microservice-spring-boot:${BUILD_NUMBER} ."
            }
        }
        
        stage("Create a container"){
            steps{
                sh "docker run -d -p 1001:1001 --name offers-microservice-spring-boot uppusrinath/offers-microservice-spring-boot:${BUILD_NUMBER}"
            }
        }
    }
}
