def home="/var/lib/jenkins/workspace/ms-cart/micro-service-starter/docker_code/zuul-api-gateway"
pipeline {
    agent any
    stages{
        stage("checkout"){
            steps{
                git branch:"main",url:"https://github.com/srinath-17/Micro_services.git"
            }
        }
      stage("Run serverip.sh"){
           steps{
             sh " chmod -x ${home}/serverip.sh"
             sh "${home}/./serverip.sh"
        stage("build Docker image"){
            steps{
                sh "docker rm -f uppusrinath/zuul:${BUILD_NUMBER} "
                sh "docker build -t uppusrinath/zuul:${BUILD_NUMBER} ${home}"
            }
        }
        
        stage("Create a container"){
            steps{
                sh "docker run -d -p 9999:9999 --name cart uppusrinath/zuul:${BUILD_NUMBER} "
            }
        }
    }
}
