//Jenkinsfile= micro-service-starter/docker_code/ui-web-app-reactjs/Jenkinsfile//
pipeline{
    agent any
    stages{
        stage("checkout scm"){
            steps{
                 checkout scm
                
            }
        }
    }
}
