//Jenkinsfile= micro-service-starter/kubernetes_code/ui-web-app-reactjs/Jenkinsfile//
def contextpath="micro-service-starter/kubernetes_code/ui-web-app-reactjs"
pipeline{
    agent any
    stages{
        stage("checkout scm"){
            steps{
                 git branch: "main",url:"https://github.com/srinath-17/Micro_services.git"
                
            }
        }
        stage("Building Dockerfile"){
            steps{
                sh "docker build -t uppusrinath/ui:${BUILD_NUMBER} ${contextpath}  "
            }
        }
    }
}
